name: Docker Image CI

on:
  push:
    branches: ["main"]
    tags: "*"

jobs:
  detect-version:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    outputs:
      tag: ${{ steps.get-version.outputs.TAG }}
    steps:
      - name: Get Tag Version
        id: get-version
        run: echo TAG=${GITHUB_REF/refs\/tags\//} >> $GITHUB_OUTPUT
  
  build:
    name: Host Build
    runs-on: ubuntu-latest
    needs: detect-version
    steps:
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
          
      - name: Use tag
        run: echo "Works. Tag is ${GITHUB_REF##*/}" #echo ${{steps.tag.outputs.tag}}
